#**1. 코랩의 성능**

###1-1. OS환경

In [1]:
!cat /etc/issue.net

Ubuntu 18.04.5 LTS

###1-2. Python 버전

In [2]:
!python --version

Python 3.7.12

#**2. 셀의 종류**

* 코드 : 파이썬 코드를 실행할 수 있는 셀
* 텍스트 : 설명을 달거나 문구등을 적기 위핸 텍스트 전용 셀 (마크다운언어)

###2-1. 셀의 삽입 방법

1. 상단의 "+코드", "+텍스트" 버튼을 눌러 삽입
2. 코드셀을 위에 삽입 : ctrl + m,a
3. 코드셀을 아래에 삽입 : ctrl + m,b

###2-2. 셀의 변경 방법

1. 코드셀을 텍스트셀로 변경 : ctrl + mm
2. 텍스트셀을 코드셀로 변경 : ctrl + my

###2-3. 단축키를 설정하는 방법

*ctrl + mh

### 2-4. 셀을 삭제하는 방법

1. 우측의 휴지통 아이콘 클릭
2. ctrl + md

# **3. 셀의 실행**

1. ctrl + enter : 해당 셀을 실행하고 커서는 해당 셀에 남음
2. shift + enter : 해당 셀을 실행하고 커서는 다음셀로 넘어감(없을경우 셀을 생성)
3. alt + enter : 해당 셀을 실행하고 커서는 다음셀을 삽입함

In [11]:
print("hello world!")

hello world!

#**4. 이미지 다루기**

In [12]:
from IPython.display import Image

In [ ]:
Image('http://t1.daumcdn.net/friends/prod/editor/dc8b3d02-a15a-4afa-a88b-989cf2a50476.jpg')

#**5. 유튜브 동영상 로딩하기**

In [15]:
from IPython.display import YouTubeVideo

In [ ]:
YouTubeVideo("1tqJSPHbS9c", 400, 300, start = 30)

#**6. 파일 업로드**

###6-1. 파일 직접 올리기

1. 좌측 메뉴 -> 5번째 '파일' -> 드래그앤드랍
2. files.upload() 함수를 사용
3. 구글드라이브에서 파일을 가져오는 방법

In [21]:
from google.colab import files

In [ ]:
myfile = files.upload()

###6-2. 구글드라이브에서 파일 가져오기

In [24]:
from google.colab import drive

In [25]:
drive.mount('/content/drive')

Mounted at /content/drive

In [26]:
filename = "/content/drive/MyDrive/Colab Notebooks/korean-idol.csv"

In [27]:
import pandas as pd

In [28]:
data = pd.read_csv(filename)

In [29]:
data

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442